# Generated by Django 5.1.3 on 2024-11-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
